// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBro.Data;

#nullable disable

namespace TradingBro.Data.Migrations
{
    [DbContext(typeof(TradingBroDbContext))]
    [Migration("20260518181026_AddLeverageAndMarginMode")]
    partial class AddLeverageAndMarginMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TradingBro.Core.Models.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnnouncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exchange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncedAt")
                        .HasDatabaseName("ix_announcements_announced_at");

                    b.HasIndex("Exchange", "ExternalId")
                        .HasDatabaseName("ix_announcements_external");

                    b.HasIndex("Exchange", "Symbol", "Market", "EventType", "AnnouncedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_announcements_dedup");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("TradingBro.Core.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<int>("Exchange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaper")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leverage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RealizedPnlUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLossPrice")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasPrecision(28, 12)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeSignalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_positions_status");

                    b.HasIndex("Exchange", "Symbol", "Status")
                        .HasDatabaseName("ix_positions_symbol_status");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TradingBro.Core.Models.TradeSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Leverage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuoteAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLossPct")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfitPct")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetExchange")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId")
                        .HasDatabaseName("ix_signals_announcement");

                    b.HasIndex("StrategyName", "CreatedAt")
                        .HasDatabaseName("ix_signals_strategy");

                    b.ToTable("trade_signals", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
