<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Binance.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingBro.Core\TradingBro.Core.csproj" />
    <ProjectReference Include="..\TradingBro.Data\TradingBro.Data.csproj" />
  </ItemGroup>

</Project>
